### ISSUE TITLE
'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by peyloride** [egegunes/redmine-cli#28]
```
Traceback (most recent call last):
  File "/home/peyloride/.local/bin/redmine", line 11, in <module>
    load_entry_point('Redmine-CLI==0.0.5', 'console_scripts', 'redmine')()
  File "/home/peyloride/.local/lib/python3.7/site-packages/redminecli/main.py", line 150, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by peyloride** [comment]
Closing as its duplicate (Thankgs GitHub!)
